name: ososs_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # GetX Ecosystem
  get: 4.6.5
  # Functional programming thingies
  dartz: ^0.10.1
  # shared preferences replacement (sync)
  get_storage: 2.1.1
  # implement a responsive layout by providing helper widgets and extensions.
  responsive_sizer: 3.1.1
  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.1.0
  # The following give informations about app (version, app name, ...)
  package_info_plus: ^3.0.3
  # The following Get current device information from within the Flutter application.
  device_info_plus: ^8.1.0
  # A composable, Future-based library for making HTTP requests.
  connectivity_plus: ^3.0.3
  dio: ^5.0.1
  # A flexible widget for user notification.
  another_flushbar: ^1.12.29
  fluttertoast: ^8.2.1
  # cached network image
  cached_network_image: ^3.2.3
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # run the following: flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  image_path: "assets/icons/icon-app-ios.png"
  android: false
  ios: true

flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/


  # To add fonts to your application, add an assets section, like this:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa_Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Lovelyn
      fonts:
        - asset: assets/fonts/Lovelyn_Regular.ttf
          weight: 400
